# Dockerfile para el servidor de subidas de fotos (Node.js)
# Usamos Node.js oficial
FROM node:26-alpine

# Configurar usuario no-root para seguridad
#RUN addgroup -g 1000 -S nodejs && \
#    adduser -S -u 1000 -G nodejs nodejs

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias de producción
RUN npm install --omit=dev

# Copiar código fuente
COPY . .

# Crear directorio /srv para subir fotos
RUN mkdir -p /srv && \
    chown nodejs:nodejs /srv

# Cambiar dueño de /app a nodejs
RUN chown -R nodejs:nodejs /app

# Usar usuario no-root
USER nodejs

# Exponer puerto
EXPOSE 3000

# Iniciar el servidor de subidas
CMD ["node", "--es-module-specifier-resolution=node", "dist/upload-server.js"]
